<form class="feedback_form ianonymous mform" autocomplete="off" action="http://moodle.mitsgwalior.in/mod/feedback/complete.php" method="POST" accept-charset="utf-8">
	<div style="display: none;" id="yui_3_17_2_1_1525502194868_122"><div class="hide" id="yui_3_17_2_1_1525502194868_121"><input type="text" class="ignoredirty" id="yui_3_17_2_1_1525502194868_120"><input type="password" class="ignoredirty" id="yui_3_17_2_1_1525502194868_128"></div><input name="id" type="hidden" value="1769">
<input name="courseid" type="hidden" value="108">
<input name="gopage" type="hidden" value="0">
<input name="lastpage" type="hidden" value="0">
<input name="startitempos" type="hidden" value="0">
<input name="lastitempos" type="hidden" value="0">
<input name="sesskey" type="hidden" value="YMnOUVMik0">
<input name="_qf__mod_feedback_complete_form" type="hidden" value="1">
</div>


	<fieldset class="hidden" id="yui_3_17_2_1_1525502194868_132"><div id="yui_3_17_2_1_1525502194868_131">
		<div id="fitem_id_anonymousmode" class="fitem femptylabel feedback_mode"><div class="fitemtitle"><div class="fstaticlabel"> </div></div><div class="felement fstatic">Mode: Anonymous</div></div>
		<div id="fitem_id_label_4269" class="fitem femptylabel feedback_itemlist feedback-item-label"><div class="fitemtitle"><div class="fstaticlabel"> </div></div><div class="felement fstatic" id="yui_3_17_2_1_1525502194868_130"><div class="no-overflow" id="yui_3_17_2_1_1525502194868_129"><p></p><h3 style="text-align:center;"><b style="color:inherit;font-family:inherit;"><img src="http://moodle.mitsgwalior.in/pluginfile.php/37156/mod_feedback/item/4269/site_logo1.png" alt="" width="209" height="162" class="img-responsive atto_image_button_text-bottom"><br></b></h3><h3 style="text-align:center;"><b style="color:inherit;font-family:inherit;">Madhav Institute of Technology &amp; Science&nbsp;</b><br></h3><h4 style="text-align:center;" id="yui_3_17_2_1_1525502194868_134"><b style="color:inherit;font-family:inherit;" id="yui_3_17_2_1_1525502194868_133">Indirect Measurement of &nbsp;Course Outcome</b><b style="color:inherit;font-family:inherit;font-size:14px;"><u>&nbsp;</u></b></h4>

<h5><b><span>Dear &nbsp;Student,</span></b></h5><h5><b><span><br></span></b><b><i><span>K</span>indly give your response on the following course outcomes after the completion of the course :&nbsp;</i></b><br></h5></div></div></div>
		<div id="fgroup_id_group_multichoice_4270" class="fitem feedback_itemlist feedback-item-multichoice feedback_hasvalue multichoice-r multichoice-vertical fitem_fgroup "><div class="fitemtitle"><div class="fgrouplabel"><label>I am able to demonstrate the basics concepts of UNIX &amp; Linux environment.<img class="req" title="Required field" alt="Required field" src="http://moodle.mitsgwalior.in/theme/image.php/clean/core/1518281518/req"> </label></div></div><fieldset class="felement fgroup"><span><input name="multichoice_4270[0]" value="0" type="radio" id="id_multichoice_4270_0_0"><label for="id_multichoice_4270_0_0">Not selected</label></span><br><span><input name="multichoice_4270[0]" value="1" type="radio" id="id_multichoice_4270_0_1"><label for="id_multichoice_4270_0_1">Strongly Agree 
</label></span><br><span><input name="multichoice_4270[0]" value="2" type="radio" id="id_multichoice_4270_0_2"><label for="id_multichoice_4270_0_2">Agree 
</label></span><br><span><input name="multichoice_4270[0]" value="not satisfied at all" type="radio" id="id_multichoice_4270_0_3" checked="checked"><label for="id_multichoice_4270_0_3">Average</label></span></fieldset></div>
		<div id="fgroup_id_group_multichoice_4271" class="fitem feedback_itemlist feedback-item-multichoice feedback_hasvalue multichoice-r multichoice-vertical fitem_fgroup "><div class="fitemtitle"><div class="fgrouplabel"><label>I am able to design a program or Application program solving real world program using Linux &amp; UNIX.<img class="req" title="Required field" alt="Required field" src="http://moodle.mitsgwalior.in/theme/image.php/clean/core/1518281518/req"> </label></div></div><fieldset class="felement fgroup error"><span class="error" tabindex="0">Required</span><br><span><input name="multichoice_4271[0]" value="0" type="radio"  id="id_multichoice_4271_0_0"><label for="id_multichoice_4271_0_0">Not selected</label></span><br><span><input name="multichoice_4271[0]" value="1" type="radio" id="id_multichoice_4271_0_1"><label for="id_multichoice_4271_0_1">Strongly Agree
</label></span><br><span><input name="multichoice_4271[0]" value="2" type="radio" id="id_multichoice_4271_0_2"><label for="id_multichoice_4271_0_2">Agree
</label></span><br><span><input name="multichoice_4271[0]" value="not satisfied at all" type="radio" id="id_multichoice_4271_0_3" checked="checked"><label for="id_multichoice_4271_0_3">Average</label></span></fieldset></div>
		<div id="fgroup_id_group_multichoice_4273" class="fitem feedback_itemlist feedback-item-multichoice feedback_hasvalue multichoice-r multichoice-vertical fitem_fgroup "><div class="fitemtitle"><div class="fgrouplabel"><label>I am able to develop a skill for understanding the concepts of Linux &amp; UNIX Programming.<img class="req" title="Required field" alt="Required field" src="http://moodle.mitsgwalior.in/theme/image.php/clean/core/1518281518/req"> </label></div></div><fieldset class="felement fgroup error"><span class="error" tabindex="0">Required</span><br><span><input name="multichoice_4273[0]" value="0" type="radio"  id="id_multichoice_4273_0_0"><label for="id_multichoice_4273_0_0">Not selected</label></span><br><span><input name="multichoice_4273[0]" value="1" type="radio" id="id_multichoice_4273_0_1"><label for="id_multichoice_4273_0_1">Strongly Agree
</label></span><br><span><input name="multichoice_4273[0]" value="2" type="radio" id="id_multichoice_4273_0_2"><label for="id_multichoice_4273_0_2">Agree
</label></span><br><span><input name="multichoice_4273[0]" value="not satisfied at all" type="radio" id="id_multichoice_4273_0_3" checked="checked"><label for="id_multichoice_4273_0_3">Average</label></span></fieldset></div>
		<div id="fgroup_id_group_multichoice_4272" class="fitem feedback_itemlist feedback-item-multichoice feedback_hasvalue multichoice-r multichoice-vertical fitem_fgroup "><div class="fitemtitle"><div class="fgrouplabel"><label>I am able to create &amp; Install the UNIX and Linux Environment.<img class="req" title="Required field" alt="Required field" src="http://moodle.mitsgwalior.in/theme/image.php/clean/core/1518281518/req"> </label></div></div><fieldset class="felement fgroup error"><span class="error" tabindex="0">Required</span><br><span><input name="multichoice_4272[0]" value="0" type="radio" id="id_multichoice_4272_0_0"><label for="id_multichoice_4272_0_0">Not selected</label></span><br><span><input name="multichoice_4272[0]" value="1" type="radio" id="id_multichoice_4272_0_1"><label for="id_multichoice_4272_0_1">Strongly Agree
</label></span><br><span><input name="multichoice_4272[0]" value="2" type="radio" id="id_multichoice_4272_0_2"><label for="id_multichoice_4272_0_2">Agree
</label></span><br><span><input name="multichoice_4272[0]" value="not satisfied at all" type="radio" id="id_multichoice_4272_0_3" checked="checked"><label for="id_multichoice_4272_0_3">Average</label></span></fieldset></div>
		<div id="fgroup_id_group_multichoice_4274" class="fitem feedback_itemlist feedback-item-multichoice feedback_hasvalue multichoice-r multichoice-vertical fitem_fgroup "><div class="fitemtitle"><div class="fgrouplabel"><label>I am able to examine different ways for Scheduling, Inter process Communication, Address Mapping in a Virtual Storage UNIX System, Working with UNIX C Files and Graphics.<img class="req" title="Required field" alt="Required field" src="http://moodle.mitsgwalior.in/theme/image.php/clean/core/1518281518/req"> </label></div></div><fieldset class="felement fgroup error"><span class="error" tabindex="0">Required</span><br><span><input name="multichoice_4274[0]" value="0" type="radio" id="id_multichoice_4274_0_0"><label for="id_multichoice_4274_0_0">Not selected</label></span><br><span><input name="multichoice_4274[0]" value="1" type="radio" id="id_multichoice_4274_0_1"><label for="id_multichoice_4274_0_1">Strongly Agree
</label></span><br><span><input name="multichoice_4274[0]" value="2" type="radio" id="id_multichoice_4274_0_2"><label for="id_multichoice_4274_0_2">Agree
</label></span><br><span><input name="multichoice_4274[0]" value="not satisfied at all" type="radio" id="id_multichoice_4274_0_3" checked="checked"><label for="id_multichoice_4274_0_3">Average</label></span></fieldset></div>
		<div class="fitem feedback_itemlist feedback-item-multichoice feedback_hasvalue multichoice-r multichoice-vertical fitem_fgroup "><div class="fitemtitle"><div class="fgrouplabel"><label>I am able to Build a Project for Electronic Mail, Usenet News &amp; Managing an Internet Web Server.</label></div></div><fieldset class="felement fgroup error"><span class="error" tabindex="0">Required</span><br><span><input name="multichoice_4275[0]" value="0" type="radio"><label for="id_multichoice_4275_0_0">Not selected</label></span><br><span><input name="multichoice_4275[0]" value="1" type="radio" id="id_multichoice_4275_0_1"><label for="id_multichoice_4275_0_1">Strongly Agree
</label></span><br><span><input name="multichoice_4275[0]" value="2" type="radio" id="id_multichoice_4275_0_2"><label for="id_multichoice_4275_0_2">Agree
</label></span><br><span><input name="multichoice_4275[0]" value="not satisfied at all" type="radio" id="id_multichoice_4275_0_3" checked="checked"><label for="id_multichoice_4275_0_3">Average</label></span></fieldset></div>
		<div  class="fitem femptylabel requirednote"><div class="fitemtitle"><div class="fstaticlabel"> </div></div><div class="felement fstatic">There are required fields in this form marked <img alt="Required field" src="http://moodle.mitsgwalior.in/theme/image.php/clean/core/1518281518/req">.</div></div>
		</div></fieldset>
	<fieldset class="hidden"><div>
		<div  class="fitem fitem_fgroup femptylabel"><div class="fitemtitle"><div class="fgrouplabel"><label> </label></div></div><fieldset class="felement fgroup"><input class="form-submit" name="savevalues" value="Submit your answers" type="submit"> <br> <input name="cancel" value="Cancel" type="submit" onclick="skipClientValidation = true; return true;" class=" btn-cancel" id="id_cancel"></fieldset></div>
		</div></fieldset>
</form>